title: Divagar.blog
description: "Memórias, reflexões e pensamentos para (sobre)viver a distopia"
url: "https://www.divagar.blog"
baseurl: ""

github_pages: true

markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: "/page:num/"

exclude:
  - .obsidian/
  - Gemfile
  - Gemfile.lock
  - vendor/