title: Divagar.blog
description: "Memórias, reflexões e pensamentos para (sobre)viver a distopia"
url: "https://benicchio79.github.io"
baseurl: "/divagar-blog"

github_pages: true

markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - .obsidian/
  - Gemfile
  - Gemfile.lock
  - vendor/
